/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LogoRouteImport } from './routes/logo'
import { Route as PrototypeGrooveRouteImport } from './routes/prototype/groove'
import { Route as PrototypeRedesignsRouteImport } from './routes/prototype/redesigns'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoRoute = LogoRouteImport.update({
  id: '/logo',
  path: '/logo',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeGrooveRoute = PrototypeGrooveRouteImport.update({
  id: '/prototype/groove',
  path: '/prototype/groove',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeRedesignsRoute = PrototypeRedesignsRouteImport.update({
  id: '/prototype/redesigns',
  path: '/prototype/redesigns',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logo': typeof LogoRoute
  '/prototype/groove': typeof PrototypeGrooveRoute
  '/prototype/redesigns': typeof PrototypeRedesignsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logo': typeof LogoRoute
  '/prototype/groove': typeof PrototypeGrooveRoute
  '/prototype/redesigns': typeof PrototypeRedesignsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/logo': typeof LogoRoute
  '/prototype/groove': typeof PrototypeGrooveRoute
  '/prototype/redesigns': typeof PrototypeRedesignsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/logo' | '/prototype/groove' | '/prototype/redesigns'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/logo' | '/prototype/groove' | '/prototype/redesigns'
  id: '__root__' | '/' | '/logo' | '/prototype/groove' | '/prototype/redesigns'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogoRoute: typeof LogoRoute
  PrototypeGrooveRoute: typeof PrototypeGrooveRoute
  PrototypeRedesignsRoute: typeof PrototypeRedesignsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logo': {
      id: '/logo'
      path: '/logo'
      fullPath: '/logo'
      preLoaderRoute: typeof LogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/groove': {
      id: '/prototype/groove'
      path: '/prototype/groove'
      fullPath: '/prototype/groove'
      preLoaderRoute: typeof PrototypeGrooveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/redesigns': {
      id: '/prototype/redesigns'
      path: '/prototype/redesigns'
      fullPath: '/prototype/redesigns'
      preLoaderRoute: typeof PrototypeRedesignsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogoRoute: LogoRoute,
  PrototypeGrooveRoute: PrototypeGrooveRoute,
  PrototypeRedesignsRoute: PrototypeRedesignsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
